filenames: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/sRNA_R29_rename_list.txt"
input_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/00_raw_fastq"
rename_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/01_renamed_snk_fq"
fastQC_bft_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/02_fastQC_BFT"
multQC_bft_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/02_fastQC_BFT/multqc"
adpt_trimmed_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/03_adpt_trimmed"
adpt_trimmed_fp_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/03_adpt_trimmed_fp"
adpt_trimmed_ca_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/03_adpt_trimmed/cutadapt"
fastQC_AT_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/04_fastQC_AT"
multQC_AT_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/04_fastQC_AT/multqc"
mapped_unfiltered_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/05_map_unfiltered"
INDEX_AT11_plus_TGS: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/genomes/TAIR10_Chr-all_Araport11+current_transgenes_R29"
size_filt_rmChloMito_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/06_size_filt_ChloMito_free"
INDEX_tRNA_rRNA: "/cluster/pixstor/slotkinr-lab/mkramer/annotations/arabidopsis/tRNA_and_rRNA.KP"
map_rRNA_tRNA_free_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/07_map_rRNA_tRNA_free"
genome_Shortstack: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_snk/genomes/TAIR10_nuclear-Chr-all_Araport11.fa"
sht_dir: "/cluster/pixstor/slotkinr-lab/sandaruwan/seq_pipelines/sRNA_round29/08_Shortstack"